#!/system/bin/sh

############################
# Custom Kernel Settings

# Define Basic Paths:

REACTOR_S_DATA="/data/BlackReactor"
REACTOR__S_LOGFILE="$REACTOR_S_DATA/initialization.log"

# block devices
SYSTEM_DEVICE="/dev/block/platform/msm_sdcc.1/by-name/system"
CACHE_DEVICE="/dev/block/platform/msm_sdcc.1/by-name/cache"
DATA_DEVICE="/dev/block/platform/msm_sdcc.1/by-name/userdata"

 mount -o remount,rw /system
 mount -o remount,rw /data

if [ ! -d $REACTOR_S_DATA ]; then
	echo "Creating Directory..."
	mkdir -p $REACTOR_S_DATA
fi

# maintain log file history
rm $REACTOR__S_LOGFILE.3
mv $REACTOR__S_LOGFILE.2 $REACTOR__S_LOGFILE.3
mv $REACTOR__S_LOGFILE.1 $REACTOR__S_LOGFILE.2
mv $REACTOR__S_LOGFILE $REACTOR__S_LOGFILE.1

# Initialize the log file (chmod to make it readable also via /sdcard link)
echo $(date) BlackReactor-Kernel initialization started > $REACTOR__S_LOGFILE
chmod 777 $REACTOR__S_LOGFILE
cat /proc/version >> $REACTOR__S_LOGFILE
echo "=========================" >> $REACTOR__S_LOGFILE
grep ro.build.version /system/build.prop >> $REACTOR__S_LOGFILE
echo "=========================" >> $REACTOR__S_LOGFILE
echo "$(date) End Log" >> $REACTOR__S_LOGFILE
echo "\n=========================\n" >> $REACTOR__S_LOGFILE